config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'admin/show'
    get 'admin/edit'
    get 'admin/update'
  end
  devise_for :admins
  devise_for :customer
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope module: :customer do
    root to: 'homes#top'
    resources :customers, only: [:show, :edit, :update]
    resources :reviews
    get 'reviews', to: 'reviews#search'
    get 'reviews', to: 'reviews/tag'
    get 'reviews', to: 'reviews/tag_index'
    resources :favorite, only: [:index, :create, :destroy]
  end
  namespace :admin do
    resources :reviews
    resources :admins, only: [:show, :edit, :update]
    get 'reviews', to: 'reviews#search'
    get 'reviews', to: 'reviews/tag'
    get 'reviews', to: 'reviews/tag_index'
    resources :customers, except: [:new, :create, :destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :reviews
  has_many :favorites, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :reviews
  has_many :favorites, dependent: :destroy
  
  
  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :admin
  belongs_to :review
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  belongs_to :admin
  has_many :tagmaps
  has_many :favorites, dependent: :destroy

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end
  
  def favorited_by?(admin)
    favorites.where(admim_id: admin.id).exists?
  end
  
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tagmaps
end

app/models/tagmap.rb
class Tagmap < ApplicationRecord
  belongs_to :review
  belongs_to :tag
end

app/controllers/admin/admin_controller.rb
class Admins::AdminController < ApplicationController
  def show
    @admin = Admin.find(params[:id])
  end

  def edit
    @admin = Admin.find(params[:id])
  end

  def update
    @admin = Admin(params[:id])
    @admin.update(admin_params)
    redirect_to admin_path(@admin.id)
  end
  
  private
  def admin_params
    params.require(:admin).permit(:email, :nickname, :birthday)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def update
    customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customers_path
  end

  private
  def customer_params
    params.require(:customer).permit(:nickname)
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController

  def index
    @reviews = Review.all.page(params[:page]).per(8)
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(params)
    if @review.save
      redirect_to admin_review_path
    else
      render new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    review = Review.find(params[:id])
    review.update(review_params)
    redirect_to admin_review_path(review)
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
    redirect_to admin_reviews_path
  end

  def search
  end

  def tag
  end

  def tag_index
  end

  private
  def review_params
    params.require(:review).permit(:name, :heading, :year, :group_name, :member, :comment, :rate)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    added_attrs = [ :last_name, :first_name, :last_name_kana, :first_name_kana, :nickname, :birthday]

    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit 
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to customer_path(@customer.id)
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :nickname, :birthday)
  end
end

app/controllers/customer/favorites_controller.rb
class Customer::FavoritesController < ApplicationController
  
  def index
  end
  
  def create
  end

  def destroy
  end
  
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  
  def top
    
  end
  
end

app/controllers/customer/reviews_controller.rb
class Customer::ReviewsController < ApplicationController

  def index
    @reviews = Review.all.page(params[:page]).per(8)
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to reviews_path
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    review = Review.find(params[:id])
    review.update(review_params)
    redirect_to review_path(review)
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
    redirect_to reviews_path
  end

  def search
  end

  def tag
  end

  def tag_index
  end

  private

  def review_params
    params.require(:review).permit(:name, :heading, :year, :group_name, :member, :comment, :rate)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admins/admin_helper.rb
module Admins::AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/favorites_helper.rb
module Customer::FavoritesHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/reviews_helper.rb
module Customer::ReviewsHelper
end

app/views/admins/customers/index.html.erb
<h3>会員一覧</h3>

<div class="container">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <table>
        <tr>
          <th>名前</th>
          <th>ニックネーム</th>
        </tr>
        <% @customers.each do |customer| %>
        <td><%= customer.full_name %></td>
        <td>
          <%= form_with model: customer, local:true do |f| %>
          <%= f.text_field :nickname, autofocus: true %>
          <%= f.submit "変更", class: "btn btn-success" %>
          <% end %>
        </td>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admins/reviews/edit .html.erb
<div class="container">
 <div class="row">
  <div class="col-md-4">
   <h2>レビューの編集画面</h2>
  </div>
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <%= link_to "削除する", admin_review_path(@review), method: :delete %>
  </div>
 </div>
  <div class="row">
    <div class="col-md-6">
      <div class="table">
        <%= form_with model: @review,url: admin_review_path local:true do |f| %>
        <tr>
          <th>曲名</th>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <th>一言で表すと</th>
          <td><%= f.text_field :heading %></td>
        </tr>
        <tr>
          <th>リリース</th>
          <td><%= f.date_select :year, discard_year %></td>
        </tr>
        <tr>
          <th>グループ名</th>
          <td><%= f.text_field :group_name %></td>
        </tr>
        <tr>
          <th>メンバー</th>
          <td><%= f.text_field :member %></td>
        </tr>
        <tr>
          <th>感想　どんな曲か</th>
          <td><%= f.text_area :comment %></td>
        </tr>
        <tr>
          <th>おすすめ度</th>
        </tr>
        <%= f.submit '保存する' %>
        <% end %>
        <script>
          $('#evaluate_stars').raty({
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            scoreName: 'review[rate]'
          });
        </script>
      </div>
    </div>
  </div>
</div>

app/views/admins/reviews/index.html.erb
<h3>レビュー一覧</h3>

<%= link_to "新規登録", new_admin_review_path %>

<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-lg-3 col-md-4 mb-12">
      <% @reviews.each do |review| %>
      <table>
        <tr>
          <th><%= review.name %></th>
          <td><%= review.year %></td>
        </tr>
        <tr>
          <th><%= review.heading %></th>
        </tr>
        <tr>
          <td class="reviwe-rate" data-score="<%= f.rate %>"></td>
        </tr>
      </table>
      <% end %>
      <script>
        $('.reviwe-rate').raty({
          readOnly: true,
          score: function() {
            return $(this).attr('data-score');
          },
          path: '/assets/'
        });
      </script>
    </div>
  </div>
  <p class="text-center">
    <%= paginate @reviews %>
  </p>
</div>

app/views/admins/reviews/new.html.erb
<h3>レビュー投稿画面</h3>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="table">
        <%= form_with model: @review,url: admin_reviews_path, local:true do |f| %>
        <tr>
          <th>曲名</th>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <th>一言で表すと</th>
          <td><%= f.text_field :heading %></td>
        </tr>
        <tr>
          <th>リリース</th>
          <td><%= f.date_select :year, {:discard_year => true} %></td>
        </tr>
        <tr>
          <th>グループ名</th>
          <td><%= f.text_field :group_name %></td>
        </tr>
        <tr>
          <th>メンバー</th>
          <td><%= f.text_field :member %></td>
        </tr>
        <tr>
          <th>感想　どんな曲か</th>
          <td><%= f.text_area :comment %></td>
        </tr>
        <tr>
          <th>おすすめ度</th>
        </tr>
        <%= f.submit '投稿' %>
        <% end %>
        <script>
          $('#evaluate_stars').raty({
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            scoreName: 'review[rate]'
          });
        </script>
      </div>
    </div>
  </div>
</div>

app/views/admins/reviews/show.html.erb
<h3>レビューの詳細</h3>

<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <%= link_to "編集画面", admin_review_path(@review) %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <table>
        <tr>
          <th>曲名</th>
          <td><%= @reviwe.name %></td>
        </tr>
        <tr>
          <th>リリース</th>
          <td><%= @reviwe.year %></td>
        </tr>
        <tr>
          <th>グループ名</th>
          <td><%= @review.group_name %></td>
        </tr>
        <tr>
          <th>メンバー</th>
          <td><%= @reviwe.member %></td>
        </tr>
      </table>
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-10">
      <table>
        <tr>
          <th>感想</th>
        </tr>
        <tr>
          <td><%= @review.comment %></td>
        </tr>
      </table>
    </div>
    <div class="col-md-9"></div>
    <div class="col-md-3">
      <table>
      <tr>
        <th>投稿者</th>
      </tr>
      <tr>
        <td>
          <% if @review.customer_id %>
          <%= @review.customer.nickname %>さん
          <% else %>
          <%= @review.admin.nickname %>さん
        </td>
      </tr>
    </table>
    </div>
  </div>
</div>

app/views/customer/customers/edit.html.erb
<h2>マイページの編集画面</h2>

<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <%= form_with model:@customer,local:true do |f| %>
      <table>
        <tr>
          <th>氏名</th>
          <td><%= f.text_field :first_name %></td>
          <td><%= f.text_field :last_name %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= f.text_field :first_name_kana %></td>
          <td><%= f.text_field :last_name_kana %></td>
        </tr>
        <tr>
          <th>ニックネーム</th>
          <td><%= f.text_field :nickname %></td>
        </tr>
        <tr>
          <th>誕生日</th>
          <td><%= f.f.date_select :birth_date, use_month_numbers: true,start_year: 1930, end_year: (Time.now.year - 1), default: Date.new(2000, 1, 1) %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= f.text_field :email %></td>
        </tr>
      </table>
    </div>
    <div class="col-md-12">
      <center>
        <%= f.submit "変更を保存する" %>
        <% end %>
      </center>
    </div>
  </div>
</div>

app/views/customer/customers/show.html.erb
<h2>マイページ</h2>

<div class="container">
  <div class="row">
    <dv class="col-md-4">
      <h5>登録情報</h5>
    </dv>
    <div class="col-md-4">
      <%= link_to "編集する", edit_customer_path(@customer), class: "btn btn-success"%>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <table>
        <tr>
          <th>名前</th>
          <td><%= @customer.full_name %></td>
        </tr>
        <tr>
          <th>カナ</th>
          <td><%= @customer.full_name_kana %></td>
        </tr>
        <tr>
          <th>ニックネーム</th>
          <td><%= @customer.nickname %></td>
        </tr>
        <tr>
          <th>誕生日（年）</th>
          <td><%= @customer.birthday %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/customer/favorites/index.html.erb
<h3>いいね一覧</h3>

app/views/customer/homes/top.html.erb
<h1>曲紹介画面</h1>

<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      
    </div>
  </div>
</div>

app/views/customer/reviews/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-4">
   <h2>レビューの編集画面</h2>
  </div>
  <div class="col-md-4"></div>
  <div class="vol-md-4">
    <%= link_to "削除する", review_path(@review), method: :delete %>
  </div>
 </div>
  <div class="row">
    <div class="col-md-6">
      <div class="table">
        <%= form_with model: @review,url: review_path local:true do |f| %>
        <tr>
          <th>曲名</th>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <th>一言で表すと</th>
          <td><%= f.text_field :heading %></td>
        </tr>
        <tr>
          <th>リリース</th>
          <td><%= f.date_select :year, discard_year %></td>
        </tr>
        <tr>
          <th>グループ名</th>
          <td><%= f.text_field :group_name %></td>
        </tr>
        <tr>
          <th>メンバー</th>
          <td><%= f.text_field :member %></td>
        </tr>
        <tr>
          <th>感想　どんな曲か</th>
          <td><%= f.text_area :comment %></td>
        </tr>
        <tr>
          <th>おすすめ度</th>
        </tr>
        <%= f.submit '保存する' %>
        <% end %>
        <script>
          $('#evaluate_stars').raty({
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            scoreName: 'review[rate]'
          });
        </script>
      </div>
    </div>
  </div>
</div>

app/views/customer/reviews/index.html.erb
<h3>曲紹介画面</h3>

<%= link_to "新規登録", new_review_path %>

<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-lg-3 col-md-4 mb-12">
      <% @reviews.each do |review| %>
      <table>
        <tr>
          <th><%= review.name %></th>
          <td><%= review.year %></td>
        </tr>
        <tr>
          <th><%= review.heading %></th>
        </tr>
        <tr>
          <td class="reviwe-rate" data-score="<%= f.rate %>"></td>
        </tr>
      </table>
      <% end %>
      <script>
        $('.reviwe-rate').raty({
          readOnly: true,
          score: function() {
            return $(this).attr('data-score');
          },
          path: '/assets/'
        });
      </script>
    </div>
  </div>
  <p class="text-center">
    <%= paginate @reviews %>
  </p>
</div>

app/views/customer/reviews/new.html.erb
<h3>レビュー投稿画面</h3>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="table">
        <%= form_with model: @review,url: reviews_path, local:true do |f| %>
        <tr>
          <th>曲名</th>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <th>一言で表すと</th>
          <td><%= f.text_field :heading %></td>
        </tr>
        <tr>
          <th>リリース</th>
          <td><%= f.date_select :year, {:discard_year => true} %></td>
        </tr>
        <tr>
          <th>グループ名</th>
          <td><%= f.text_field :group_name %></td>
        </tr>
        <tr>
          <th>メンバー</th>
          <td><%= f.text_field :member %></td>
        </tr>
        <tr>
          <th>感想　どんな曲か</th>
          <td><%= f.text_area :comment %></td>
        </tr>
        <tr>
          <th>おすすめ度</th>
        </tr>
        <%= f.submit '投稿' %>
        <% end %>
        <script>
          $('#evaluate_stars').raty({
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            scoreName: 'review[rate]'
          });
        </script>
      </div>
    </div>
  </div>
</div>

app/views/customer/reviews/new_html.erb
<h3>レビュー投稿画面</h3>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="table">
        <%= form_with model: @review,url: reviews_path local:true do |f| %>
        <tr>
          <th>曲名</th>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <th>一言で表すと</th>
          <td><%= f.text_field :heading %></td>
        </tr>
        <tr>
          <th>リリース</th>
          <td><%= f.date_select :year, discard_year %></td>
        </tr>
        <tr>
          <th>グループ名</th>
          <td><%= f.text_field :group_name %></td>
        </tr>
        <tr>
          <th>メンバー</th>
          <td><%= f.text_field :member %></td>
        </tr>
        <tr>
          <th>感想　どんな曲か</th>
          <td><%= f.text_area :comment %></td>
        </tr>
        <tr>
          <th>おすすめ度</th>
        </tr>
        <%= f.submit '投稿' %>
        <% end %>
        <script>
          $('#evaluate_stars').raty({
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            scoreName: 'review[rate]'
          });
        </script>
      </div>
    </div>
  </div>
</div>

app/views/customer/reviews/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h2>曲詳細</h2>
    </div>
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <% if current_customer %>
      <%= link_to "編集する", edit_review_path(@reviwe) %>
      <% else%>
      <%= %>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-4">
      <table>
        <tr>
          <th>曲名</th>
          <td><%= @reviwe.name %></td>
        </tr>
        <tr>
          <th>リリース</th>
          <td><%= @reviwe.year %></td>
        </tr>
        <tr>
          <th>グループ名</th>
          <td><%= @review.group_name %></td>
        </tr>
        <tr>
          <th>メンバー</th>
          <td><%= @reviwe.member %></td>
        </tr>
      </table>
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-10">
      <table>
        <tr>
          <th>感想</th>
        </tr>
        <tr>
          <td><%= @review.comment %></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="col-md-9"></div>
  <div class="col-md-3">
    <table>
      <tr>
        <th>投稿者</th>
      </tr>
      <tr>
        <td>
          <% if @cutomer %>
          <%= @customer.nickname %>さん
          <% else %>
          <%= @admin.nickname %>さん
          <% end %>
        </td>
      </tr>
    </table>
  </div>
</div>

app/views/customer/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/customer/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>