config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'admin/show'
    get 'admin/edit'
    get 'admin/update'
  end
  devise_for :admins
  devise_for :customer
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope module: :customer do
    root to: 'homes#top'
    resources :customers, only: [:show, :edit, :update]
    resources :reviews
    get 'reviews', to: 'reviews#search'
    get 'reviews', to: 'reviews/tag'
    get 'reviews', to: 'reviews/tag_index'
    resources :favorite, only: [:index, :create, :destroy]
  end
  namespace :admin do
    resources :reviews
    resources :admins, only: [:show, :edit, :update]
    get 'reviews', to: 'reviews#search'
    get 'reviews', to: 'reviews/tag'
    get 'reviews', to: 'reviews/tag_index'
    resources :customers, except: [:new, :create, :destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :reviews
  has_many :favorites, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :reviews
  has_many :favorites, dependent: :destroy
  
  
  def full_name
    self.last_name + " " + self.first_name
  end

  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :admin
  belongs_to :review
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  belongs_to :admin
  has_many :tagmaps
  has_many :favorites, dependent: :destroy

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end
  
  def favorited_by?(admin)
    favorites.where(admim_id: admin.id).exists?
  end
  
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tagmaps
end

app/models/tagmap.rb
class Tagmap < ApplicationRecord
  belongs_to :review
  belongs_to :tag
end

app/controllers/admin/admin_controller.rb
class Admins::AdminController < ApplicationController
  def show
    @admin = Admin.find(params[:id])
  end

  def edit
    @admin = Admin.find(params[:id])
  end

  def update
    @admin = Admin(params[:id])
    @admin.update(admin_params)
    redirect_to admin_path(@admin.id)
  end
  
  private
  def admin_params
    params.require(:admin).permit(:email, :nickname, :birthday)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def update
    customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customers_path
  end

  private
  def customer_params
    params.require(:customer).permit(:nickname)
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController

  def index
    @reviews = Review.all.page(params[:page]).per(8)
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(params)
    if @review.save
      redirect_to admin_review_path
    else
      render new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    review = Review.find(params[:id])
    review.update(review_params)
    redirect_to admin_review_path(review)
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
    redirect_to admin_reviews_path
  end

  def search
  end

  def tag
  end

  def tag_index
  end

  private
  def review_params
    params.require(:review).permit(:name, :heading, :year, :group_name, :member, :comment, :rate)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    added_attrs = [ :last_name, :first_name, :last_name_kana, :first_name_kana, :nickname, :birthday]

    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
  end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  
  def top
    
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admins/admin_helper.rb
module Admins::AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/favorites_helper.rb
module Customer::FavoritesHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/reviews_helper.rb
module Customer::ReviewsHelper
end

app/views/admins/admin/edit.html.erb
<h3>編集画面</h3>

<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <% form_with model: @admin,url: admin_admin_path(@admin) local:true do |f|%>
      <table>
        <tr>
          <th>ニックネーム</th>
          <td><%= f.text_field :nickname, autofocus: true %></td>
        </tr>
        <tr>
          <th>誕生日</th>
          <td><%= f.date_select :birth_date, use_month_numbers: true,start_year: 1930, end_year: (Time.now.year - 1), default: Date.new(2000, 1, 1) %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= f.email_field :email, autofocus: true, autocomplete: "email" %></td>
        </tr>
      </table>
      <%= f.submit "変更を保存" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/admin/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-2">
      <h3><strong>マイページ</strong></h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-2">
      <table>
        <tr>
          <th><strong>登録情報</strong></th>
          <th><%= link_to "編集する", edit_admin_path(@admin), class: "btn btn-success" %></th>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-6">
      <table>
        <tr>
          <th>ニックネーム</th>
          <td><%= @admin.nickname %></td>
        </tr>
        <tr>
          <th>誕生日</th>
          <td><%= @admin.birthday %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @admin.email %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "登録", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicGarden</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if customer_signed_in? %>
          <li class="nav-item">
           <%= link_to "マイページ", customer_path(current_customer.id), class: "btn btn-outline-dark" %>
          </li>
          <li class="nav-item">
            <%= link_to "レビュー一覧", reviews_path, class: "btn btn-outline-dark" %>
          </li>
          <li class="nav-item">
            <%= link_to "いいね一覧", favorite_index_path, class: "btn btn-outline-dark" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト",  destroy_customer_session_path, method: :delete, class: "btn btn-outline-dark" %>
          </li>
          <% elsif admin_signed_in? %>
          <li class="nav-item">
            <%= link_to "レビュー一覧", admin_reviews_path, class: "btn btn-outline-dark" %>
          </li>
          <li class="nav-item">
            <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-dark" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-dark" %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "レビュー一覧", reviews_path, class: "btn btn-outline-dark" %>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-dark" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-dark" %>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </body>

  <body>
    <%= yield %>
  </body>
</html>